In [155]:
include(joinpath(dirname(Base.active_project()), "ClassImport.jl"))
using HDF5, JSON
using .ClassImport: GreedyRegression, Integrate, ReportModel, PickSubdomains, EnvelopePol, FUNCTION_PATH, HDF5_PATH, JSON_PATH

p::Array{Float64} = Float64[]
t::Array{Float64} = Float64[]
u::Array{Float64} = Float64[]
v::Array{Float64} = Float64[]
x::Array{Float64} = Float64[]
y::Array{Float64} = Float64[]
Bx::Array{Float64} = Float64[]
By::Array{Float64} = Float64[]

h5open(joinpath(HDF5_PATH, "ieuler", "data-0.001.hdf5"), "r") do file
    global p = read(file, "result")["value"]["p"]["value"]
    global t = read(file, "result")["value"]["t"]["value"]
    global u = read(file, "result")["value"]["u"]["value"]
    global v = read(file, "result")["value"]["v"]["value"]
    global x = read(file, "result")["value"]["x"]["value"]
    global y = read(file, "result")["value"]["y"]["value"]
    global Bx = read(file, "result")["value"]["Bx"]["value"]
    global By = read(file, "result")["value"]["By"]["value"]
end

64×64×100 Array{Float64, 3}:
[:, :, 1] =
  1.91803     1.00198    -0.275205   …   2.38745    -2.47589    -3.15215
 -1.24078    -1.90366     1.49391       -2.09717    -1.63232    -1.23562
  0.144488   -0.295033    0.635839      -2.00809     0.0290181   0.570309
  2.83167     2.7425     -2.16195        2.84136     0.0460408  -1.69576
  0.706678    0.571443   -1.87822        0.609294    0.0517381  -0.561702
 -0.69685    -1.27174     1.87563    …  -4.44061    -0.852666    3.25498
  0.436526    2.05466     3.02849       -1.48153    -1.57813     0.507911
 -1.69839     2.73039     1.25526        2.23038     0.986473   -2.81218
 -3.8008     -2.38738     2.92179       -0.887656    1.40441     1.84
 -1.18918    -3.50157     4.99969       -2.20691    -2.85054     3.66016
  0.0763191   1.37775     1.33759    …   1.6705     -2.2892     -2.74582
 -1.95112     1.80055    -1.35395        2.00197     3.21916    -3.69089
 -0.764622   -2.26797     0.146277      -1.75058     2.86165     2.29518
  ⋮       

In [156]:
nw::Int = 64 # number of domains we integrate over 
dof::Int = 1 # scalars have one degree of freedom
dim::Int = 3 # how many dimensions does our data have?
env_pow::Int = 4 # weight is (1-x^2)^power
size_vec::Vector{Int} = [16,16,20] # how many gridpoints should we use per integration?
buffer::Int = 0 # Don't use points this close to boundary

pol::Matrix{Float64} = EnvelopePol.envelope_pol(env_pow, dim)

size_of_data::Vector{Int} = [64, 64, 100]
seed::Int = 42
corners::Matrix{Int} = PickSubdomains.pick_subdomains(size_of_data, size_vec, buffer, nw, seed)

grid::Vector{Vector{Float64}} = [vec(y), vec(x), vec(t)]
corners

3×64 Matrix{Int64}:
 31  22  23  34  33   8  30  33  22  …   6   4  41  46  11  32  14  18  41
 33  34  17   4  10  47  18  38  35     18  29  17  13  16  18  27  15  44
 20  55  29  76  57  35  44  11  67     55  70  52  60  12  19  48  42  12

In [157]:
using Statistics

G::Matrix{Float64} = zeros(Float64, dof*nw, 0)
labels::Vector{String} = String[]
scales::Vector{Float64} = Float64[]

function add_library_term(label::AbstractString, data::AbstractArray, derivs::AbstractVector{Int64}, scale::AbstractFloat)
    col::Vector{Float64} = Integrate.poly_integrate(data, derivs, grid, corners, size_vec, pol)

    global G = hcat(G, col)
    push!(labels, label)
    push!(scales, scale)
end

# flow terms
add_library_term("∂u/∂x", u, [2], 1.)
add_library_term("∂v/∂x", v, [2], 1.)
add_library_term("∂u/∂y", u, [1], 1.)
add_library_term("∂v/∂y", v, [1], 1.)
add_library_term("∂u/∂t", u, [3], 1.)
add_library_term("∂v/∂t", v, [3], 1.)
add_library_term("∂u^2/∂x", u .* u, [2], 1.)
add_library_term("∂uv/∂x", u .* v, [2], 1.)
add_library_term("∂uv/∂y", u .* v, [1], 1.)
add_library_term("∂v^2/∂y", v .* v, [1], 1.)

# flow terms second derivatives
add_library_term("∂^2u/∂x^2", u, [2,2], 1.)
add_library_term("∂^2u/∂y^2", u, [1,1], 1.)
add_library_term("∂^2v/∂x^2", v, [2,2], 1.)
add_library_term("∂^2v/∂y^2", v, [1,1], 1.)

# pressure terms
add_library_term("∂P/∂x", p, [2], 1.)
add_library_term("∂P/∂y", p, [1], 1.)

# B field terms
add_library_term("∂Bx^2/∂x", Bx .* Bx, [2], 1.)
add_library_term("∂Bx^2/∂y", Bx .* Bx, [1], 1.)
add_library_term("∂By^2/∂x", By .* By, [2], 1.)
add_library_term("∂By^2/∂y", By .* By, [1], 1.)
add_library_term("∂BxBy/∂x", Bx .* By, [2], 1.)
add_library_term("∂BxBy/∂y", Bx .* By, [1], 1.)
add_library_term("∂Bx/∂t", Bx, [3], 1.)
add_library_term("∂By/∂t", By, [3], 1.)

# B field second derivatives
add_library_term("∂^2Bx/∂x^2", Bx, [2, 2], 1.)
add_library_term("∂^2By/∂x^2", By, [2, 2], 1.)
add_library_term("∂^2Bx/∂y^2", Bx, [1, 1], 1.)
add_library_term("∂^2By/∂y^2", By, [1, 1], 1.)

# weird terms
add_library_term("∂uBy/∂x", u .* By, [2], 1.)
add_library_term("∂vBx/∂x", v .* Bx, [2], 1.)
add_library_term("∂uBy/∂y", u .* By, [1], 1.)
add_library_term("∂vBx/∂y", v .* Bx, [1], 1.)

# error
add_library_term("h∂^2Bx/∂t^2", Bx, [3,3], 0.001)
add_library_term("h∂^2By/∂t^2", By, [3,3], 0.001)
add_library_term("h∂^2u/∂t^2", u, [3,3], 0.001)
add_library_term("h∂^2v/∂t^2", v, [3,3], 0.001)

# forcing
add_library_term("sin(x)", sin.(permutedims(repeat(stack(fill(x, 64)), 100), (3,2,1))), Int64[], 1.)
add_library_term("sin(y)", sin.(permutedims(repeat(stack(fill(y, 64)), 100), (2,3,1))), Int64[], 1.)
add_library_term("cos(x)", cos.(permutedims(repeat(stack(fill(x, 64)), 100), (3,2,1))), Int64[], 1.)
add_library_term("cos(y)", cos.(permutedims(repeat(stack(fill(y, 64)), 100), (2,3,1))), Int64[], 1.)

norm_vec::Vector{Float64} = Integrate.poly_integrate(0*u .+ 1, Int64[], grid, corners, size_vec, pol)
G ./= norm_vec
G ./= scales'

G

64×40 Matrix{Float64}:
 -0.358469    -0.18655    0.45368     …  -0.501564  -0.72288   -0.83681
  0.201272    -0.180282  -0.474279        0.328674  -0.65518   -0.918581
  0.116964    -0.377128  -0.397122        0.237054  -0.65518   -0.946373
  0.232259     0.443731   1.02555        -0.72288    0.501564  -0.65518
 -0.0435087    1.00475    0.744044       -0.65518   -0.047871  -0.72288
 -0.279832    -0.432795  -1.09132     …   0.965052   0.501564   0.143152
 -0.204523     0.272576   0.414317       -0.417128  -0.72288   -0.881942
 -0.00034116   0.080197  -0.383685       -0.65518   -0.328674  -0.72288
  0.108282    -0.523526  -0.579134        0.328674  -0.581171  -0.918581
 -0.571655    -0.743053   0.496849        0.83681   -0.237054  -0.501564
  0.237091     0.379998   0.838413    …  -0.581171   0.501564  -0.783618
 -0.142803    -0.653353   0.525116       -0.501564  -0.65518   -0.83681
  0.118557     0.309875  -0.138271        0.72288    0.417128  -0.65518
  ⋮                               

In [ ]:
x

64×64×100 Array{Float64, 3}:
[:, :, 1] =
 0.0        0.0        0.0        …  0.0        0.0        0.0
 0.0981748  0.0981748  0.0981748     0.0981748  0.0981748  0.0981748
 0.19635    0.19635    0.19635       0.19635    0.19635    0.19635
 0.294524   0.294524   0.294524      0.294524   0.294524   0.294524
 0.392699   0.392699   0.392699      0.392699   0.392699   0.392699
 0.490874   0.490874   0.490874   …  0.490874   0.490874   0.490874
 0.589049   0.589049   0.589049      0.589049   0.589049   0.589049
 0.687223   0.687223   0.687223      0.687223   0.687223   0.687223
 0.785398   0.785398   0.785398      0.785398   0.785398   0.785398
 0.883573   0.883573   0.883573      0.883573   0.883573   0.883573
 0.981748   0.981748   0.981748   …  0.981748   0.981748   0.981748
 1.07992    1.07992    1.07992       1.07992    1.07992    1.07992
 1.1781     1.1781     1.1781        1.1781     1.1781     1.1781
 ⋮                                ⋱                        
 5.10509    5.10509    

In [158]:
using LinearAlgebra

gamma::Float64 = 1.5

for i::Int = 1:5
    cs::Matrix{Float64}, residuals::Vector{Float64}, _ = GreedyRegression.greedy_regression(G)
    println(findall((residuals[1:end-1]) ./ (residuals[2:end]) .> gamma))

    k::Int, _, _, eqs::String = ReportModel.report_identified_model(cs, residuals, scales, labels, gamma)

    col_norms::Vector{Float64} = [norm(G[:, j] .* cs[j, k]) for j = 1:size(G, 2)]
    kill::Int = argmax(col_norms)
    G = G[:, setdiff(1:end, kill)]
    labels = labels[setdiff(1:end, kill)]
    scales = scales[setdiff(1:end, kill)]

    println(eqs)
end

[1]
∂u/∂x + ∂v/∂y = 0
[1, 5, 6, 7, 8, 9]
∂u/∂t + ∂u^2/∂x + ∂uv/∂y - 0.016∂^2u/∂x^2 - 0.016∂^2u/∂y^2 + ∂P/∂x - ∂Bx^2/∂x - ∂BxBy/∂y - 0.0h∂^2u/∂t^2 - cos(y) = 0
[1, 6, 7, 8, 9]
∂v/∂t + ∂uv/∂x + ∂v^2/∂y - 0.016∂^2v/∂x^2 - 0.016∂^2v/∂y^2 + ∂P/∂y - ∂By^2/∂y - ∂BxBy/∂x - 0.0h∂^2v/∂t^2 + cos(x) = 0
[1, 2, 3, 4, 5]
∂Bx/∂t - 0.016∂^2Bx/∂x^2 - 0.016∂^2Bx/∂y^2 - ∂uBy/∂y + ∂vBx/∂y - 0.001h∂^2Bx/∂t^2 = 0
[2, 3, 4]
∂By/∂t - 0.016∂^2By/∂x^2 - 0.016∂^2By/∂y^2 + ∂uBy/∂x - ∂vBx/∂x = 0
